# Generated by Django 5.2.5 on 2025-09-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(default='This is my default summar!')),
            ],
        ),
    ]
